# Generated by Django 5.1.15 on 2026-05-28 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_remove_product_visibility_flags'),
        ('products', '0002_remove_product_visibility_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_recommended',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Recommended product'),
        ),
        migrations.AddField(
            model_name='product',
            name='recommended_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Recommended sort order'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_recommended', 'recommended_order'], name='products_pr_is_reco_9c6a7d_idx'),
        ),
    ]
