# Generated by Django 5.1.15 on 2026-05-28 23:36

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0003_recommended_products'),
        ('shipping', '0002_alter_city_is_active_alter_city_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='billing_city_name',
            field=models.CharField(max_length=120, verbose_name='Billing city name'),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_postal_code',
            field=models.CharField(max_length=20, verbose_name='Billing postal code'),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_street',
            field=models.CharField(max_length=255, verbose_name='Billing street'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Delivery date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='first_name',
            field=models.CharField(max_length=120, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='order',
            name='flexible_delivery',
            field=models.BooleanField(default=False, verbose_name='Flexible delivery'),
        ),
        migrations.AlterField(
            model_name='order',
            name='guest_email',
            field=models.EmailField(help_text='Used for guest orders and order tracking.', max_length=254, verbose_name='Guest email'),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_name',
            field=models.CharField(max_length=120, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_notes',
            field=models.TextField(help_text='Required at checkout — delivery instructions.', verbose_name='Order notes'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(db_index=True, max_length=32, unique=True, verbose_name='Order number'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on delivery')], default='cod', max_length=20, verbose_name='Payment method'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=32, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='shipping.city', verbose_name='Shipping city'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_city_name',
            field=models.CharField(help_text='City name as entered by customer.', max_length=120, verbose_name='Shipping city name'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='shipping.shippingmethod', verbose_name='Shipping method'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_postal_code',
            field=models.CharField(max_length=20, verbose_name='Shipping postal code'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Shipping price'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_street',
            field=models.CharField(max_length=255, verbose_name='Shipping street'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='products.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_name',
            field=models.CharField(max_length=255, verbose_name='Product name'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='sku',
            field=models.CharField(max_length=64, verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Unit price'),
        ),
    ]
