# Generated by Django 5.1.15 on 2026-06-01 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_notes_optional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='billing_city_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='billing_postal_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='billing_street',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='flexible_delivery',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_method',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_postal_code',
        ),
    ]
