# Generated by Django 5.1.15 on 2026-06-01 20:45

from django.db import migrations, models


def mark_existing_orders_read(apps, schema_editor):
    Order = apps.get_model("orders", "Order")
    Order.objects.all().update(is_new=False)


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_legacy_checkout_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_new',
            field=models.BooleanField(db_index=True, default=True, help_text='Marked as read when opened in admin.', verbose_name='New (unread)'),
        ),
        migrations.RunPython(mark_existing_orders_read, migrations.RunPython.noop),
    ]
