# Generated by Django 5.1.15 on 2026-07-14 11:56

from django.db import migrations, models


def migrate_cod_to_cash(apps, schema_editor):
    Order = apps.get_model("orders", "Order")
    Order.objects.filter(payment_method="cod").update(payment_method="cash")


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_order_requested_delivery_date"),
    ]

    operations = [
        migrations.RunPython(migrate_cod_to_cash, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[("card", "Pay by card"), ("cash", "Pay in cash")],
                default="cash",
                max_length=20,
                verbose_name="Payment method",
            ),
        ),
    ]
