# Generated by Django 5.1.15 on 2026-05-28 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='newsletter_opt_in',
        ),
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('shipping', 'Shipping'), ('billing', 'Billing')], default='shipping', max_length=20, verbose_name='Address type'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=120, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='address',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Default address'),
        ),
        migrations.AlterField(
            model_name='address',
            name='label',
            field=models.CharField(blank=True, max_length=64, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(max_length=20, verbose_name='Postal code'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street_line_1',
            field=models.CharField(max_length=255, verbose_name='Street line 1'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street_line_2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Street line 2'),
        ),
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=32, verbose_name='Phone'),
        ),
    ]
