# Generated by Django 5.1.15 on 2026-05-28 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_legacy_cms'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Email')),
                ('first_name', models.CharField(blank=True, max_length=120, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, max_length=120, verbose_name='Last name')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Phone')),
                ('order_count', models.PositiveIntegerField(default=0, verbose_name='Orders placed')),
                ('registered_at', models.DateTimeField(blank=True, null=True, verbose_name='Registered at')),
                ('first_seen_at', models.DateTimeField(auto_now_add=True, verbose_name='First seen')),
                ('last_seen_at', models.DateTimeField(auto_now=True, verbose_name='Last activity')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_contacts', to=settings.AUTH_USER_MODEL, verbose_name='User account')),
            ],
            options={
                'verbose_name': 'customer contact',
                'verbose_name_plural': 'customer contacts',
                'ordering': ['-last_seen_at'],
            },
        ),
    ]
