# Generated by Django 5.1.15 on 2026-06-01 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customer_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
