# Generated by Django 5.1.15 on 2026-06-01 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercontact',
            name='delivery_city_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Delivery city'),
        ),
        migrations.AddField(
            model_name='customercontact',
            name='delivery_street',
            field=models.CharField(blank=True, max_length=255, verbose_name='Delivery street'),
        ),
    ]
