# Generated by Django 5.1.15 on 2026-05-28 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='categories/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='categories.category', verbose_name='Parent'),
        ),
        migrations.AlterField(
            model_name='category',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Sort order'),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='categorytranslation',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='categorytranslation',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160, verbose_name='Meta description'),
        ),
        migrations.AlterField(
            model_name='categorytranslation',
            name='meta_title',
            field=models.CharField(blank=True, max_length=70, verbose_name='Meta title'),
        ),
        migrations.AlterField(
            model_name='categorytranslation',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='categorytranslation',
            name='slug',
            field=models.SlugField(max_length=220, unique=True, verbose_name='Slug'),
        ),
    ]
