# Generated by Django 5.1.15 on 2026-05-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HeroBannerTranslation",
        ),
        migrations.DeleteModel(
            name="HeroBanner",
        ),
        migrations.DeleteModel(
            name="PromoSectionTranslation",
        ),
        migrations.DeleteModel(
            name="PromoSection",
        ),
        migrations.DeleteModel(
            name="HomepageSection",
        ),
        migrations.DeleteModel(
            name="SocialLink",
        ),
        migrations.AlterField(
            model_name="footersettings",
            name="email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="footersettings",
            name="phone",
            field=models.CharField(blank=True, max_length=32, verbose_name="Phone"),
        ),
        migrations.AlterField(
            model_name="footersettingstranslation",
            name="address",
            field=models.TextField(blank=True, verbose_name="Address"),
        ),
        migrations.AlterField(
            model_name="footersettingstranslation",
            name="working_hours",
            field=models.TextField(blank=True, verbose_name="Working hours"),
        ),
        migrations.AlterField(
            model_name="sitesettingstranslation",
            name="default_meta_description",
            field=models.CharField(
                blank=True,
                max_length=160,
                verbose_name="Default meta description",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettingstranslation",
            name="default_meta_title",
            field=models.CharField(blank=True, max_length=70, verbose_name="Default meta title"),
        ),
        migrations.AlterField(
            model_name="sitesettingstranslation",
            name="site_name",
            field=models.CharField(
                default="Kod Pendule",
                max_length=120,
                verbose_name="Site name",
            ),
        ),
    ]
