# Generated by Django 5.1.15 on 2026-05-29 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0003_shippingmethod_bilingual'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingmethod',
            options={'ordering': ['name_sr'], 'verbose_name': 'shipping method', 'verbose_name_plural': 'shipping methods'},
        ),
    ]
