# Generated by Django 5.1.15 on 2026-06-01 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_legacy_checkout_fields'),
        ('shipping', '0004_alter_shippingmethod_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShippingMethod',
        ),
    ]
